---
title: "Polarised pandemic response: a comparison of Democrat and Republican leadership
  responses to the COVID-19 pandemic in the US"
author: 
  - Courtney Morgan^[csmorgan@umich.edu]
  - Haihan Zhang^[hhzhang@umich.edu]
  - Soumik Purkayastha^[soumikp@umich.edu]
date: ''
output: pdf_document
link-citations: yes
subtitle: "BIOSTAT 625 term project"
bibliography: biblio.bibtex
---

# Abstract

## _Introduction_
The impact of political affiliation in leading the fight against the spread of COVID-19 has been a hotly-debated issue in the United States with sparse empirical evidence. We aim to assess how political affiliation of state governors affected the state's  ability to control the pandemic. 

## _Methods_
We evaluate mean and median time-varying reproductive numbers for the 50 United States and Washington D.C. by means of graphical devices and 2-sample bootstrap-based comparisons. In addition to this unadjusted analysis, we control for variation in population and public health-preparedness prior to onset of the pandemic to investigate if political affiliation of a state's governor had any significant association with the spread of pandemic in the United States. By means of a principal component analysis, we incorporate information from six Public Health Index (PHI) scores into a linear regression framework.   

## _Results_
The difference (Republican - Democrat) in means for mean time-varying reproductive numbers is (1.1649-1.1722), with 95% bootstrap confidence interval (-0.017, 0.031). Similarly, the difference in medians for median time-varying reproductive numbers is (1.0812-1.063), with 95% bootstrap confidence interval (-0.042, 0.006). Treating mean time varying $R(t)$ as the response and adjusting for population density, PHI scores and gender of governor, the estimated coefficient of political affiliation  of governor (case group: Republican, control group: Democrat) is 0.04	(95% CI: -0.52 to 0.60).

## _Conclusion_
While there may be latent confounding factors, our analysis does not show political affiliation of state governors to be significantly associated with control of the pandemic in the United States. 

\newpage
 
 
# 1. Introduction
 
Coronavirus disease 2019 (COVID-19) is a contagious disease caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). New cases of COVID-19 are increasing rapidly at astonishing rates globally; as of December 2020, more than 67 million cases have been detected, which have led to more than 1.5 million fatalities [@wiki2020covid] The volume and speed of data generation in biomedical literature, social media, and other resources during the COVID-19 pandemic is unprecedented [@hechenbleikner2020data] and presents a massive stress test with many unexpected opportunities for data science. Collaborating with researchers from various other fields, data scientists have been instrumental in tracking the contagion and trying to make sense of its many challenges.
 
Many articles have shown the interest in investigating the relationship between leadership and response patterns to the pandemic, and have led to political and social implications. Americans have changed their behavior in ways that would have been unthinkable even a few months ago. Masks are an essential accessory. Social distancing is the norm. And even as states moved to reopen their economies in May and June, many Americans continued to think it was better for people to stay home. But underneath that apparent consensus is a large — and growing — partisan divide. As the number of coronavirus cases surged in many states across the United States, Republicans and Democrats increasingly viewed the disease in starkly different ways, from the personal health risks arising from the coronavirus outbreak to their comfort in engaging in everyday activities. According to recent surveys [@pew2020party], Republicans have consistently been less likely than Democrats to say that they fear being hospitalized because of COVID-19 or that they might unknowingly spread the virus to others. But on the other hand, that partisan gap has widened significantly between April and June. For example, Neelon et. al. revealed the quantitative differences in response strategies between Democrat and Republican-led states in the United States [@neelon2020associations]. 

Another recent study implied that there is a significant and systematic difference by gender of the leader of a region (e.g. a state or country) in various public health metrics for controlling the spread of the pandemic [@garikipati2020leading]. Women leaders reacted more quickly and decisively in the face of potential fatalities through earlier lockdown than male leaders in similar circumstances [@nyt2020women]. This is not a coincidence just in the context of this pandemic. Past studies [@schubert1999financial] have implied that women leaders may be less willing to take risks with lives but more willing to accept risks in relation to the early lockdown of economies [@borghans2009gender]. Based on these findings, subsequent studies have suggested that leadership characteristics other than risk attitudes may also systematically differ between men and women [@eagly1990gender].
 
@purkayastha2020women explored how the  gender of heads of state was associated with the control of the pandemic around the world. The approach relied on comparing $R(t)$ - the effective time-varying reproduction number [@cori2013new] at time $t$ to assess the pandemic control at different time points. Given the imbalance in group sizes (the study compared 19 countries led by women with 140 countries led by men), the authors chose to use resampling techniques to implement a two-group comparison of mean and median values of $R(t)$. No significant association between gender and timely control of the pandemic was reported. We suspect that this unadjusted analysis has been severely affected by confounding factors. For example, population and public health preparedness prior to onset of the pandemic have been revealed to be important factors in how well a region is able to contain spread of the disease. 

In this report, we first explore the relationship between political affiliation of a state governor in the United States and pandemic control through visual inspection and unadjusted statistical inference using simple bootstrap-based group comparisons. Next, we investigate if said association is significant after controlling for gender of governor, public health preparedness and population of state by means a linear regression model. National Health Security Preparedness Index (NHSPI) [@phi2020index]
is a  group of six measures (such as health security surveillance, community planning and engagement and others) that take into account readiness for disease outbreaks. These indices were incorporated into our analysis to control for confounding. 


# 2. Methods

All data we used were from online public resources. We obtained the gender and political affiliation of state governors from [Wikipedia](https://en.wikipedia.org/wiki/List_of_current_United_States_governors). The COVID-19 data for the United States were collected from [The New York Times' Github repository](https://github.com/nytimes/covid-19-data) . The state-wise population counts were obtained from [Wikipedia](https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population) as well. The National Health Security Preparedness Index (NHSPI) was extracted from its [official website](https://nhspi.org/).
 
We restrict our analysis to states with at least 1000 cumulative reported cases of COVID-19 infections and at least 10 days of reported data as of November 9, 2020. Our study duration ends on that date, which coincides with the [first vaccine being announced](https://www.bbc.com/news/health-54873105). For all states in our pool study units, we compute the time-varying $R(t)$. Then, we calculated the mean, median, maximum and last $R(t)$ over the study duration of the pandemic for each state based on the computed $R(t)$ trajectories. We present density plots of these summaries stratified by the political affiliation of state governors. In addition to visual inspection, we also did some formal statistical inference. For median, mean, maxima and last values of time-varying $R(t)$, we performed a two-sample bootstrap procedure-based comparison of group-wise medians for all the summary statistics mentioned above and constructed 95% CI based on empirical $2.5$-th and $97.5$-th percentile of the bootstrap distributions. Next, we perform an adjusted comparison of pandemic control of the states in our study, when stratified by political affiliation of the state governor. By controlling for variation due to gender of governor, population and public health preparedness prior to onset of the pandemic, we study a linear regression model using the mean of $R(t)$ as outcome and political affiliation of state governor as the covariate of interest. Since the range of the mean of $R(t)$ in different states is quite small, we inverse-normalise the response variable. Instead of naively using all six public health indices in our model, we use principal component analysis to reduce the dimension of said indices from six to three. The top three principal components used explain about $75\%$ of the variation in the public health indices. 

The subsequent sections present our findings and discuss the implications of the same.











# 3. Results

## 3.1. Summary statistics (Table 1)

The table below presents an overview of the data we analyse in this report. Of the $53$ states and territories considered, $27$ are led by Democrats, while the other $26$ are led by Republicans. Stratifying by gender, $8$ are female while $45$ are male. 




## 3.2. Boxplots (Figure 1)

Figure 1 provides a general view of the distribution of $R(t)$ in different states and the political affiliation of state governors. The boxplots were truncated above for all values $R(t) \geq 3.5$, to focus on the majority of $R(t)$ values. Values of $R(t)$ below one are desirable, however, we observed that the median of $R(t)$ is above one for all states, except for Guam and District of Columbia. The summary from this stratified boxplot is that though the pandemic seemed to be slowing down as of November 9, it was not under control. Values of $R(t) \leq 1$ indicate that the contagion is under control. 




## 3.3. Stratified density plots (Figure 2)

Figure 2(A) shows a similar distribution of mean values of $R(t)$ for Republican-led or Democrat-led states. The median values of the stratified distributions are very close to each other, and are approximately equal to $1.16$. Figure 2(B) reveals a slight shift in the political affiliation-stratified distributions of median values of $R(t)$ --- they have more probability weight towards smaller values for Democrat-led states (the lower the $R(t)$, the slower the transmission), although the medians of the stratified distributions are quite similar again --- $1.06$ for Democrat-led states, and $1.08$ for Republican-led states. Figure 2(C) indicates a slight shift in the political affiliation-stratified distributions of maximum values of $R(t)$, but has opposite diretion to Figure 2(B) --- Democrat-led states are more likely to have larger maximum of value of $R(t)$, with an median of statistic being $3.89$, comparing to Republican-led states' $3.64$. Figure 2(D) shows that the distribution of the most recent value of $R(t)$ is quite identical between Democrat-led and Republican-led states. The median of the the most recent value of $R(t)$ for Democrat-led states is $1.40$, while that for Republican-led states is $1.39$.




## 3.4. Unadjusted bootstrap-based comparison (Table 2)

The results of two-sample bootstrap procedure-based comparison for the statistics are summarized in Table 2. For each bootstrap sample from ether group, we compute the median of the associated statistic (mean, median, maxima and most recent values of $R(t)$) and consider their differences (Democrat --- Republican). We note the 95% bootstrap-based confidence intervals all contain zero, which indicates that the differences of median of statistics between Republican-led and Democrat-led states are not statistically significant at 5% level of significance. Our findings are based on $B = 1000$ bootstrap replications. We abstain from a detailed discussion on how two sample bootstrap methods are implemented. For more information, please see @efron1983leisurely. 




## 3.5. Adjusted linear models-based comparison

We adjust for variation in the response (mean of time varying $R(t)$) due to variation in population of a state, gender of governor as well as some indices which quntify the state's public health safety by means of some indices. 

The indices combine measures from multiple sources and perspectives to offer a broad view of the health protections in place for the nation as a whole and for each U.S. state. They identify strengths as well as gaps in the protections needed to keep people safe and healthy in the face of large-scale public health threats, and it tracks how these protections vary across the United States and change over time. The areas of focus include (a) health security surveillance, (b) community planning and engagement, (c) incident and information management, (d) healthcare delivery, (e) countermeasure management and (e) environmental and occupational health. All these areas are of critical importance when managing a pandemic. Using data from the National Health Security Preparedness Index [website](https://nhspi.org/), we obtain information regarding these indices for all the states and territories in our study. However, instead of using all six indices, we implement a principal components analysis to find the top three principal components based on these indices - together, those three PCs explain about $75\%$ of the variation due to the public health indices. 

### 3.5.1. Principal component analysis of Public Health Indices (Table 3)

The table below presents a summary of the six principal components, of which the first three are chosen as covariates in our linear model. This is done with the aim of adjusting for state-level variation in public health preparedness prior to the onset of the pandemic. 




### 3.5.2. Linear model (Table 4)

We consider the mean of the time-varying $R(t)$ as the response variable. The linear model under investigation is as follows

$$\mathbb{E}(y^{mean}_i) = \beta_0 + 
\beta_1 \cdot {I}(\text{party}_i = \text{Republican}) + \beta_2\cdot {I}(\text{gender}_i = \text{male}) + 
\beta_3\cdot \text{pop}_i + 
\beta_4 \cdot PC^{PH}_1 + \beta_5 \cdot PC^{PH}_2 + \beta_6 \cdot PC^{PH}_3$$

where $y^{\text{mean}}_i$ is the mean of time-varying $R(t)$ for the $i$-th state/territory in our analysis. $\text{party}_i$ is an indicator variable denoting party affiliation of the governor of the $i$-th state/territory. Similarly,  $\text{gender}_i$ denotes gender. $\text{pop}_i$ denotes population and $PC^{PH}_j \ (1 \leq j \leq 3)$ denote the three principal components associated with the six public health indices. We are interested in the significance of $\beta_1$. The table below summarises our findings. 



The linear regression model used inverse-normalized mean values of $R(t)$ as outcome; gender and political affiliation of state governor, state population and the top three principal components of National Health Security Preparedness Index (NHSPI) as covariates. Based on the analytical results of the linear regression, we do not find any significant association between political affiliation and the response, even after adjusting for (potential) confounding factors. Based on the table above, only the state population is statistically significant for the mean value of $R(t)$ at 5% level of significance (p-value = 0.002). This is not an unexpected finding, since the disease is known to spread quickly in larger populations as compared to smaller ones [@bhadra2020impact]. 


# 4. Discussion

This study of factors in pandemic controls was conducted in a two-step manner. With the scope of all 51 states in the United States, we first explored the relationship between the political affiliation and pandemic control. Although we listed all four statistics of interest in the summary Table 1, we do prefer to use the mean or median for the assessment. The maximum value of $R(t)$ reflected the worst scenario during the whole pandemic period. Take New York as an example, the high maximum value of $R(t)$ was more due to the outburst at the very beginning of the pandemic, however, the governor actually did a quite good job to get it under control, so we do not think the maximum value of $R(t)$ is objective for the assessment of pandemic control. Similarly, the last value of $R(t)$ represented the last available record in our collected data, so some states like Hawaii, which had relatively stable progress during the pandemic, cannot be considered as convincing examples of good pandemic control. Therefore, we only compared two measures (mean and median) summarizing the trajectory of time varying reproduction number $R(t)$ in Figure 2 and Figure 3. However, we only observed minor differences between Republican-led and Democrat-led states. This observation was supported by the two-sample bootstrap procedure-based comparison for the statistics. The mean values of difference of the statistic between two groups from bootstrap sampling are all close to zero, and the 95% CIs also contain zero.
 
For the second step of this study, we took both gender and political affiliation of state governors into a linear regression model, together with state population and PCs of NHSPI. We assumed NHSPI may have strong effects on the pandemic control, because it reflected the preparedness of public health emergencies like COVID-19. However, the analytical results from the linear model revealed that none of the top three PCs of NHSPI were significant for the mean of $R(t)$. Neither gender nor political affiliation of state governor was statistically significant adjusting for the rest of the covariates. The only relevant factor is the state population. This is reasonable, since states with large populations like New York, California did suffer a lot in pandemic control. And our study can be supportive to other studies exploring the relationship between population and the pandemic control.

\newpage
 
# References
